### ISSUE TITLE
Report Issues in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#10]
**Browser:**
Firefox

**Notes:**
For “Report Issues” in Firefox, some equivalent links would be:
* Bugs: https://bugzilla.mozilla.org/describecomponents.cgi?product=DevTools
* Forum: https://discourse.mozilla.org/c/devtools/213
* Twitter: https://twitter.com/FirefoxDevTools
* YouTube: https://www.youtube.com/playlist?list=PLgjjGlfBflIRRWuCXnSTU1-35EcDc5Jwf
(there might be others)

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=report-issues&browser=Firefox
