### ISSUE TITLE
Test social media previews in Polypane 16

### ISSUE THREAD

**Issue by pankajparashar** [pankajparashar/canidev.tools#104]
Polypane 16: shows social media preview for [canidev.tools](https://www.canidev.tools/), but the X (formerly twitter) website does not :-/

<img width="840" alt="Screenshot 2023-11-04 at 16 59 49" src="https://github.com/pankajparashar/canidev.tools/assets/38640616/e590beff-68f0-4c96-ac4a-47eee8a07488">

---
<img width="607" alt="image" src="https://github.com/pankajparashar/canidev.tools/assets/38640616/c7aa41bf-8c2b-4ab7-a723-b5e8a233e8fe">

/cc @Kilian

**Comment by Kilian** [comment]
Will investigate on monday!

**Comment by Kilian** [comment]
Try adding some more twitter meta tags, at least a twitter:title and og:title, as it might require a title to be there even if that's no longer shown. 

```html
<meta property="og:title" content="Can I DevTools?">
<meta property="og:url" content="https://www.canidev.tools">
<meta property="og:type" content="website">
<meta property="og:description" content="It is like @CanIUse, but for the browser devtools, created by Pankaj Parashar and curated by community.">

<meta name="twitter:title" content="Can I DevTools?">
<meta name="twitter:creator" content="@CanIDevTools">
<meta name="twitter:site" content="@CanIDevTools">
<meta name="twitter:description" content="It is like @CanIUse, but for the browser devtools, created by Pankaj Parashar and curated by community.">
```

**Comment by pankajparashar** [comment]
Interesting, I'm using @nextjs OpenGraph/Twitter APIs to automatically generate the meta tags described here,
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image

I'll check if there is a way to manually override the output to add the title meta tags. Thanks!

**Comment by pankajparashar** [comment]
@Kilian You are a genius! I can see the twitter card in its full glory now! Perhaps, Polypane can be slightly clever by alerting the developer that lack of title meta tags could mean that the cards wont render as expected.

<img width="605" alt="image" src="https://github.com/pankajparashar/canidev.tools/assets/38640616/49243f6c-cad2-45b3-958c-e68e01116f77">

**Comment by Kilian** [comment]
Definitely adding that in the next release!
