### ISSUE TITLE
Web vitals status in Polypane

### ISSUE THREAD

**Issue by pankajparashar** [pankajparashar/canidev.tools#106]
It appears that the UI for the web vitals status has changed since this article was published, https://polypane.app/docs/web-vitals/.

I can no longer see the "eye" icon next to CLS and LCP. The numbers are all in zeroes and the UI looks a bit tad different than the demos in the article.

<img width="844" alt="image" src="https://github.com/pankajparashar/canidev.tools/assets/38640616/3099c25a-0aac-4fc6-8518-436aac9b7ba9">

@kilian

**Comment by Kilian** [comment]
In more recent versions of chromium web vitals only get communicated after user interaction to the page, and Polypane only shows an eye icon when it got element information for CLS/LCP. Same for the bars, which are only shown when there's data from CrUX to compare to.

canidev.tools:
![Screenshot from 2023-11-22 11-25-47](https://github.com/pankajparashar/canidev.tools/assets/41970/23f84d26-44c5-4902-a352-705ef24b5131)

polypane.app:
![Screenshot from 2023-11-22 11-26-56](https://github.com/pankajparashar/canidev.tools/assets/41970/f8a65605-d813-4f83-a196-8e9844a6a7fe)
