### ISSUE TITLE
Debug scroll overflow in Polypane

### ISSUE THREAD

**Issue by pankajparashar** [pankajparashar/canidev.tools#108]
/cc @Kilian
Following the steps [outlined here](https://github.com/pankajparashar/canidev.tools/blob/v3/features/debug-scroll-overflow.hjson#L18), I couldn't get the layout debugger to highlight the element causing the overflow in red, just like it is described in [this article](https://polypane.app/blog/strategies-for-dealing-with-horizontal-overflows/). Am I doing anything wrong here?

https://github.com/pankajparashar/canidev.tools/assets/38640616/916f5814-70f7-473e-a7fd-35d53ddfff3c

**Comment by Kilian** [comment]
That causes an overflow in a div, Polypane only detects overflows on the `documentElement`/`window` (see how your header stays in place).

**Comment by pankajparashar** [comment]
Interesting, I don't think that the article mentions this fact, or maybe I overlooked while reading. Either ways thanks!
