### ISSUE TITLE
Drag Drop element

### ISSUE THREAD

**Issue by FrankySnow** [pankajparashar/canidev.tools#11]
**Browser:**
Firefox

**Platform:**
Windows

**Notes:**
Drag & dropping DOM nodes is also possible in Firefox, exactly like in Chrome

**Media:**
n/a

**References:**
n/a

**Comment by pankajparashar** [comment]
Duplicate of #3. 
https://www.canidev.tools/?id=drag-drop-element&browser=Firefox

**Comment by FrankySnow** [comment]
Sorry for the duplicate, and thank you for your work !
