### ISSUE TITLE
Clear console

### ISSUE THREAD

**Issue by reloadedhead** [pankajparashar/canidev.tools#12]
**Browser:**
Safari

**Platform:**
macOS

**Notes:**
Clearing the JavaScript console is available in Safari by pressing `⌘ + K`.

**Media:**
![Safari with the console being cleared](https://user-images.githubusercontent.com/41745430/172320871-464aee02-7d3d-43af-8dcf-750502186d51.mov)

**References:**
- [MDN Article](https://developer.mozilla.org/en-US/docs/Web/API/console/clear) for `console.clear()`
- [Can I Use](https://caniuse.com/mdn-api_console_clear)

**Comment by jakub-g** [comment]
Available also in Firefox 🪣 button 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1437027/172338672-94cd3250-0ba4-4e8a-bcca-5e279ee7fab3.png">

**Comment by pankajparashar** [comment]
@reloadedhead I did not know that Can I Use also covered console APIs. Thanks for the references.
https://www.canidev.tools/?id=clear-console&browser=Safari

@jakub-g Thanks
https://www.canidev.tools/?id=clear-console&browser=Firefox
