### ISSUE TITLE
Proposal to merge with devtoolstips.org

### ISSUE THREAD

**Issue by captainbrosset** [pankajparashar/canidev.tools#13]
Hi there @pankajparashar!

I'm the maintainer of the https://devtoolstips.org website and came across canidev.tools recently. It occurred to me that we have very similar goals here. I created devtoolstips for exactly the same reason you did: to have a more comprehensive coverage of all devtools features, across browsers, and not just chrome devtools (which a lot of sites out there already have). More about why I started the project [over on my blog](https://patrickbrosset.com/articles/2021-07-01-introducing-devtools-tips/).

It seems to me like we're trying to maintain the same type of information. It's not presented in the same way, but we each have a list of features and which browsers support them. For canidev.tools, it's in an airtable. For devtoolstips, it's in a series of markdown files ([see an example here](https://github.com/captainbrosset/devtools-tips/blob/main/src/tips/en/add-new-devices.md), look at the tags in the front matter part of the file).

Now, while I don't have any specific proposal here, I do believe that joining forces would help us have more impact, and minimize the maintenance cost of both our projects.
What do you think?

**Comment by pankajparashar** [comment]
Hey Patrick, Good to hear from you.

I recently stumbled upon devtoolstips.org and loved the in-depth style description of devtools features. I can't imagine the amount of effort and time it takes to document each feature in such vivid detail. I'm sucker for writing docs as well.

I wish I had discovered devtoolstips.org much earlier or at least before I started with [canidev.tools](https://www.canidev.tools/). I completely agree with you that both the projects were built on the same underlying principle and have the same objective to provide a catalogue of devtools features across multitude of browsers. 

Only distinction that I see is devtoolstips.org follows a much more elaborate style of feature description (each could be a blog post of its own) while canidev.tools has a more succint style notes focussed on concrete set of steps to use that feature. 

I'm not quite what's the path forward from here, but happy to join the forces for a single cause and take this discussion further. Let's take this offline (on email or something else you prefer)?
