### ISSUE TITLE
Output data as table in Firefox

### ISSUE THREAD

**Issue by georapbox** [pankajparashar/canidev.tools#14]
**Browser:**
Firefox

**Platform:**
MacOS, Windows, Linux

**Notes:**
Output data as table in Firefox

**Media:**
![Screenshot 2022-06-07 at 12 20 58 PM](https://user-images.githubusercontent.com/6596039/172345182-edfcae42-773f-4a7f-9c86-8e1a20934811.png)

**References:**
https://developer.mozilla.org/en-US/docs/Web/API/console/table#browser_compatibility

**Comment by pankajparashar** [comment]
Thanks! https://www.canidev.tools/?id=output-data-table&browser=Firefox
