### ISSUE TITLE
Output data as table in Safari

### ISSUE THREAD

**Issue by georapbox** [pankajparashar/canidev.tools#15]
**Browser:**
Safari

**Platform:**
MacOS

**Notes:**
Output data as table in Safari

**Media:**
![Screenshot 2022-06-07 at 12 28 19 PM](https://user-images.githubusercontent.com/6596039/172346768-a858aebd-e5d5-4013-8b79-4fa908f0c39c.png)

**References:**
https://developer.mozilla.org/en-US/docs/Web/API/console/table#browser_compatibility

**Comment by pankajparashar** [comment]
Thanks - https://www.canidev.tools/?id=output-data-table&browser=Safari
