### ISSUE TITLE
Emulate color schemes for Safari

### ISSUE THREAD

**Issue by Haroenv** [pankajparashar/canidev.tools#16]
**Browser:**
Safari

**Platform:**
macOS
**Notes:**

defaults to system color scheme

**Media:**

<img width="1439" alt="Screenshot 2022-06-07 at 14 58 23" src="https://user-images.githubusercontent.com/6270048/172385638-faef607d-34d7-4629-af4d-e3a75e72a580.png">

**References:**

Couldn't find anything on Webkit.org, but there's at least this other reference: https://stackoverflow.com/a/65588220/3185307

**Comment by pankajparashar** [comment]
Thanks! https://www.canidev.tools/?id=emulate-color-schemes&browser=Safari
