### ISSUE TITLE
Error in "Search files " for Firefox

### ISSUE THREAD

**Issue by piradix** [pankajparashar/canidev.tools#17]
**Browser:**
Firefox

**Platform:**
Windows

**Notes:**

**Media:**
(eg., video/image links)

**References:**
Search files : in network tab , in the left top conner  input the "Url Filter" select url/file  like Chrome.
![firefox search file](https://user-images.githubusercontent.com/64977993/172453378-f6fc4f6e-53ca-4c95-85ea-ff8ecc93178b.png)

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=filter-requests&browser=Chrome
