### ISSUE TITLE
View cascade layers

### ISSUE THREAD

**Issue by Haroenv** [pankajparashar/canidev.tools#18]
**Browser:**
Safari

**Platform:**

macOS

**Notes:**

I think this is only in safari tech preview for now

**Media:**

<img width="1440" alt="Screenshot 2022-06-08 at 16 06 56" src="https://user-images.githubusercontent.com/6270048/172637513-f3731ab2-ae33-4cd8-a4b4-b53f3079e726.png">

**References:**

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=view-cascade-layers&browser=Safari
