### ISSUE TITLE
Add lines for Flexbox and CSS Grid 

### ISSUE THREAD

**Issue by mstolze** [pankajparashar/canidev.tools#19]
**Browser:**
Supported in Chrome, Firefox, and Edge (Safari?)

https://developer.chrome.com/docs/devtools/css/flexbox/
https://developer.chrome.com/docs/devtools/css/grid/

https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_flexbox_layouts/index.html
https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_grid_layouts/index.html

https://devtoolstips.org/tips/en/tweak-grid-flex-alignment/

https://webkit.org/blog/11588/introducing-css-grid-inspector/

**Comment by pankajparashar** [comment]
CSS Grid:
https://www.canidev.tools/?id=inspect-css-grid&browser=Chrome

**Comment by pankajparashar** [comment]
CSS Flexbox:
https://www.canidev.tools/?id=inspect-css-flexbox&browser=Chrome
