### ISSUE TITLE
Accessibility features in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#2]
**Browser:**
Firefox

**Platform:**
All, I think

**Notes:**
“View accessibility tree” and “Simulate vision deficiencies” are also in Firefox.

**Media:**
<img width="1075" alt="Screenshot 2022-06-03 at 09 18 26" src="https://user-images.githubusercontent.com/923008/171806897-81f8f492-1f54-408f-828a-7d83d48697d3.png">
<img width="882" alt="Screenshot 2022-06-03 at 09 17 51" src="https://user-images.githubusercontent.com/923008/171806933-09928778-986d-4b7a-a0dd-fb0af23f120f.png">

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/accessibility_inspector/

**Comment by pankajparashar** [comment]
Super thanks for the screenshots!

Added:
1. https://www.canidev.tools/?id=simulate-vision-deficiencies&browser=Firefox
2. https://www.canidev.tools/?id=view-accessibility-tree&browser=Firefox
