### ISSUE TITLE
View the ARIA attribute of an element

### ISSUE THREAD

**Issue by Haroenv** [pankajparashar/canidev.tools#21]
**Browser:**
Safari

**Platform:**

macOS

**Notes:**

This has been available since a long time as far as I can tell 

**Media:**

<img width="1440" alt="Screenshot 2022-06-13 at 10 44 20" src="https://user-images.githubusercontent.com/6270048/173315272-25125191-020c-4855-8a70-04d0264088cc.png">

**References:**

https://www.sitepen.com/blog/accessibility-inspectors-a-basic-guide mentions it too

**Comment by pankajparashar** [comment]
Great job! Added: https://www.canidev.tools/?id=view-aria-attrs&browser=Safari
