### ISSUE TITLE
[suggestion] [deobfuscate-js] Deobfuscating JS string 

### ISSUE THREAD

**Issue by marwanpro** [pankajparashar/canidev.tools#25]
Firefox can deobfuscate JS UTF-8 string and some pattern

https://bugzilla.mozilla.org/show_bug.cgi?id=762761

**Comment by pankajparashar** [comment]
I'm not sure where and how to use this? The bug report is quite old and doesn't indicate how to use this feature.

I imagine after the introduction of source maps, de-obfuscation might no longer be needed
