### ISSUE TITLE
Drag-n-drop element in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#3]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Drag-n-Drop element” is also in Firefox

**Media:**
https://user-images.githubusercontent.com/923008/171807571-2fb33940-d393-40ea-9418-8277ccdd76c3.mp4

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_html/index.html#drag-and-drop

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=drag-drop-element&browser=Firefox
