### ISSUE TITLE
[detect-memory-leaks] [safari] Safari can do this by comparing heap snapshots in the Timelines Tab

### ISSUE THREAD

**Issue by dcrousso** [pankajparashar/canidev.tools#32]
see the **Detecting JavaScript Leaks** section of [Memory Debugging with Web Inspector](https://webkit.org/blog/6425/memory-debugging-with-web-inspector/)

**Comment by pankajparashar** [comment]
Looks like the article has outdated content. The screenshots shows `JavaScript Allocations` which has now been renamed to `JavaScript & Events`. Step 3 is to take a snapshot after each repetition, but it doesn't tell how? Also I don't see the Snapshot Lists & Compare button to compare two snapshots. `console.takeHeapSnapshot()` also doesn't seem to do anything.

Latest s/s:
<img width="836" alt="detect-memory-leaks-safari" src="https://user-images.githubusercontent.com/38640616/177787560-c11c05a6-bb2e-4aa9-bf36-e519735c7da5.png">

**Comment by dcrousso** [comment]
the [**JavaScript Allocations** timeline](https://webkit.org/web-inspector/timelines-tab/#javascript-allocations-timeline) is disabled by default.  you first need to enable it via the **Edit** button in the [**Events** view](https://webkit.org/web-inspector/timelines-tab/#events-view)

**Comment by pankajparashar** [comment]
Perfect thanks. Updated,

https://www.canidev.tools/detect-memory-leaks/safari
