### ISSUE TITLE
[drag-drop-element] [safari] Safari can do this

### ISSUE THREAD

**Issue by dcrousso** [pankajparashar/canidev.tools#35]
dragging and dropping in the [Elements Tab](https://webkit.org/web-inspector/elements-tab/) is supported as described for other browsers

it's also possible to drop an element in the Console to log it's JS value, or drag items from the Classes view in the [Styles panel](https://webkit.org/web-inspector/elements-tab/#styles-panel) of the [details sidebar](https://webkit.org/web-inspector/web-inspector-interface/#details-sidebar) onto the [main DOM tree](https://webkit.org/web-inspector/elements-tab/#dom-tree) in the [Elements Tab](https://webkit.org/web-inspector/elements-tab/) to add new classes to the element under the mouse

**Comment by pankajparashar** [comment]
https://www.canidev.tools/drag-drop-element/safari
