### ISSUE TITLE
Find element with XPath in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#4]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Find element with XPath” is in Firefox

**Media:**
<img width="407" alt="Screenshot 2022-06-03 at 09 25 44" src="https://user-images.githubusercontent.com/923008/171807795-c28697c9-2411-4e2e-9bc5-42a525ca1310.png">

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_html/index.html#xpath-search

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=find-by-xpath&browser=Firefox
