### ISSUE TITLE
[find-unused-javascript] [safari] Safari has JavaScript code coverage profiling

### ISSUE THREAD

**Issue by dcrousso** [pankajparashar/canidev.tools#42]
https://webkit.org/blog/3846/type-profiling-and-code-coverage-profiling-for-javascript/

**Comment by pankajparashar** [comment]
The screenshots in the link have "Debugger" & "Resources" tab, which is nowhere to be found in today's Safari. I think it was replaced by the "Sources" tab.

Link: 
https://www.canidev.tools/find-unused-javascript/safari
