### ISSUE TITLE
[view-in-3d] [chrome] Chrome has Layers panel

### ISSUE THREAD

**Issue by kshmidt** [pankajparashar/canidev.tools#44]
More info:
1) https://www.sencha.com/blog/hidden-gems-in-chrome-developer-tools/#Layers_Panel
2) https://blog.logrocket.com/eliminate-content-repaints-with-the-new-layers-panel-in-chrome-e2c306d4d752/#:~:text=can%20help%20us.-,Layers%20panel,-While%20spotting%20reflows

P.S. I believe all Chromium browsers have this functionality as well (Edge, Opera...)

**Comment by pankajparashar** [comment]
- [x] https://www.canidev.tools/view-in-3d/chrome
- [x] https://www.canidev.tools/view-in-3d/opera
