### ISSUE TITLE
[find-in-files] [chrome] Chrome has search in Resources

### ISSUE THREAD

**Issue by kshmidt** [pankajparashar/canidev.tools#46]
More info: https://developer.chrome.com/docs/devtools/search/

P.S. I believe all Chromium browsers have this functionality as well (Edge, Opera...)

**Comment by pankajparashar** [comment]
- [x] https://www.canidev.tools/find-in-files/chrome
- [x] https://www.canidev.tools/find-in-files/edge
- [x] https://www.canidev.tools/find-in-files/opera
