### ISSUE TITLE
Event listeners in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#5]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Debug event listeners” is in Firefox

**References:**
- https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_event_listeners/index.html
- https://firefox-source-docs.mozilla.org/devtools-user/debugger/set_event_listener_breakpoints/index.html

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=debug-event-listeners&browser=Firefox
