### ISSUE TITLE
HWB colours in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#6]
**Browser:**
Firefox

**Platform:**
All?

**Notes:**
“Edit hwb color format” is in Firefox

**Media:**
<img width="455" alt="Screenshot 2022-06-03 at 09 33 41" src="https://user-images.githubusercontent.com/923008/171809173-37aea9c7-d60f-4207-a4bb-15a12d000d21.png">

**References:**
Also as an optional default: https://firefox-source-docs.mozilla.org/devtools-user/settings/index.html#inspector

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=hwb-color-format&browser=Firefox
