### ISSUE TITLE
CSS `scroll-snap`

### ISSUE THREAD

**Issue by argyleink** [pankajparashar/canidev.tools#64]
Chromium DevTools support CSS scroll-snap padding, margin, alignment, and more. Here's a screenshot. You can turn it on right next to where you turn on grid support 👍🏻 

![Screenshot 2022-10-12 3 27 43 PM](https://user-images.githubusercontent.com/1134620/195451234-9d627cc2-1c5c-4453-bad8-71c56a6c9c51.png)

**Comment by pankajparashar** [comment]
Awesome! Your demo is stunning.

It's live here, [canidev.tools/inspect-scroll-snap/chrome](https://www.canidev.tools/inspect-scroll-snap/chrome), and current browser support is here,

![inspect-scroll-snap](https://user-images.githubusercontent.com/38640616/195492275-6cfed8ed-91d2-4a96-a7c8-d415aed3185f.png)
