### ISSUE TITLE
Colour schemes in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#7]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Emulate color schemes” is in Firefox.

**Media:**
<img width="183" alt="Screenshot 2022-06-03 at 09 36 01" src="https://user-images.githubusercontent.com/923008/171809597-2e092e3b-1729-481b-990b-efdb90a0dad3.png">

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_css/index.html#examine-css-rules

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=emulate-color-schemes&browser=Firefox
