### ISSUE TITLE
Print styles in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#8]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Emulate print styles” is in Firefox

**Media:**
![Screenshot from 2022-06-04 19-03-21](https://user-images.githubusercontent.com/923008/172017705-e87c477d-36b0-41b3-be96-dfd76c1167aa.png)

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_and_edit_css/index.html#view-media-rules-for-print

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=emulate-print-styles&browser=Firefox
