### ISSUE TITLE
XHR breakpoints in Firefox

### ISSUE THREAD

**Issue by nclm** [pankajparashar/canidev.tools#9]
**Browser:**
Firefox

**Platform:**
all?

**Notes:**
“Debug XHR/Fetch calls” is in Firefox

**Media:**
![Screenshot from 2022-06-04 19-11-04](https://user-images.githubusercontent.com/923008/172018019-7734ea05-7c9b-423c-b96a-75f55d41d9df.png)

**References:**
https://firefox-source-docs.mozilla.org/devtools-user/debugger/set_an_xhr_breakpoint/index.html

**Comment by pankajparashar** [comment]
https://www.canidev.tools/?id=debug-fetch-calls&browser=Firefox
