### ISSUE TITLE
[open-devtools-new-tab] [firefox] Firefox has `-devtools` command line parameter

### ISSUE THREAD

**Issue by myfonj** [pankajparashar/canidev.tools#90]
It is said to be listed in `firefox -help | more`.

See:
- https://wiki.mozilla.org/Firefox/CommandLineOptions#-devtools
- https://stackoverflow.com/questions/43235299/open-firefox-devtools-programmatically-with-firefoxprofile

**Comment by pankajparashar** [comment]
Thanks! 
https://www.canidev.tools/open-devtools-new-tab/firefox
