### ISSUE TITLE
Add Polypane to Tabler icons

### ISSUE THREAD

**Issue by pankajparashar** [pankajparashar/canidev.tools#97]
**Can I DevTools?** uses [Tabler Icons](https://tabler-icons.io/), which provides nice theme-able, resize-able vector icons that can be used as React components. It would be nice to have Polypane added to the list of browser icons. /cc @Kilian

<img width="1286" alt="image" src="https://github.com/pankajparashar/canidev.tools/assets/38640616/c0a1cebd-6c03-4937-bc6c-cfd232391731">

**Comment by Kilian** [comment]
Let me try making a tabler-icon style Polypane icon!

**Comment by Kilian** [comment]
here you go: ![brand-polypane](https://github.com/pankajparashar/canidev.tools/assets/41970/5c1057f9-0d13-46f8-b1cd-0cc2d430fc9d)

**Comment by pankajparashar** [comment]
Looks incredible! Thank you!
